### ISSUE TITLE
Non root users

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/devcontainer-features#4]
> The tests are failing on images with non-root users, as Juliaup and Julia are installed only for the root user at the moment.

https://github.com/JuliaLang/devcontainer-features/blob/60ffc2ed6038ddadba74be815814ac656fde4e14/src/julia/install.sh#L29

_Originally posted by @eitsupi in https://github.com/JuliaLang/devcontainer-features/issues/3#issuecomment-1371053367_

**Comment by davidanthoff** [comment]
So we have to think a bit about this because the general idea of Juliaup is that it is a per-user install... Specific Julia channels that are installed are _always_ going to be per-user, as they are installed into the Julia depot, i.e. `~/.julia`. Are there best practices for this kind of situation?

**Comment by eitsupi** [comment]
I recalled that there was a process for this in another Feature. It was the same easy fix. (#5)
https://github.com/meaningful-ooo/devcontainer-features/blob/2177b402ef965dd7a9d5fd5464e8ee7673096b7e/src/fish/install.sh#L116
