### ISSUE TITLE
Add to the collections index

### ISSUE THREAD

**Issue by eitsupi** [JuliaLang/devcontainer-features#8]
https://containers.dev/collections

The julia Feature seems to be working well, so it would be good to add this repository to the index.
Once registered in the index, it will appear in the VS Code and Codespaces UI.

Note: There is currently no document URL set for Julia Feature, consider merging #7 and publishing a new version.

**Comment by eitsupi** [comment]
@davidanthoff friendly reminder :)

**Comment by eitsupi** [comment]
@davidanthoff Is it ok if I do this? (only send a Pull Request to https://github.com/devcontainers/devcontainers.github.io)

**Comment by eitsupi** [comment]
@davidanthoff Could you take a look at this?

**Comment by eitsupi** [comment]
@davidanthoff Could you take a look at this?

**Comment by eitsupi** [comment]
> Is it still not indexed?

Not registered. See here. <https://containers.dev/features>

**Comment by eitsupi** [comment]
> What needs to happen to register this? The PR to [devcontainers.github.io](https://github.com/devcontainers/devcontainers.github.io) has to come from somebody in particular or anyone can do it?

I suppose anyone could do this, but I am not sure if it is worth registering as this repository appears to be unmaintained. (The index should also list where issues should be reported to, but clearly this repository is not a good place to report issues)

**Comment by davidanthoff** [comment]
I think we should go forward with registering this repo here. @eitsupi and it would probably make sense to give you full access to this repo here, if you are interested in co-maintaining it? You clearly have a better timing and grasp of things here than me ;)

**Comment by davidanthoff** [comment]
Ok, I looked through things a bit more, and I have one more question: I think in addition to the Julia feature, we'll _also_ want a `Julia` template, just so that we have a really easy way for folks to get started.

Presumably we would want to have that template here in this repo as well, right? So would it make sense to rename this repo to just `devcontainer`? Because it would not just hold a feature, but also a template?

**Comment by davidanthoff** [comment]
Yes, agreed, I would definitely want to have a feature _and_ a template. I think in my mind the new template would essentially just replace the old (now deprecated) Julia VS Code devcontainer.

**Comment by davidanthoff** [comment]
So, looking through this more, I think we are actually better off to put the template into a new repo named `JuliaLang/devcontainer-templates`. That seems to be the pattern widely used, i.e. to have separate repos for features and templates, and that gives us the best naming, plus we don't break anyone who is using this repo already. So I'll for now just register this repo here, and then we can add the template repo as well.

**Comment by davidanthoff** [comment]
https://github.com/JuliaLang/devcontainer-templates is created, now we "just" need to customize that so that it has a useful Julia template in there :) I suggest we track that over in that new repo. @eitsupi would be awesome if you could help with the template, as I don't really know what I'm doing ;)

**Comment by eitsupi** [comment]
@davidanthoff Glad you came back and took this forward!
Of course I can take on the management of this repository (I already manage https://github.com/rocker-org/devcontainer-features, https://github.com/meaningful-ooo/devcontainer-features, and https://github.com/mamba-org/devcontainer-features).

I see you have already progressed ahead, but to add, I believe the Spec specified that the Dev Container Features and Templates distribution should be done in separate repositories.

**Comment by davidanthoff** [comment]
@eitsupi great! I just invited you to a team here in JuliaLang that should give you write access to the two repos. Fantastic to have you officially on board :)

**Comment by davidanthoff** [comment]
Oh, and I'm closing this, as we are now just waiting for the PR upstream to be merged, so nothing more to do here.
